name: Continuous integration tasks
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] 
    steps:
            #      - name: get software
            #        - os: ubuntu-latest 
            #          run: |
            #            sudo apt-get update
            #            sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev libopenblas-base libopenblas-dev doxygen
            #        - os: macos-latest
            #          run: |
            #            brew update
            #            brew install m4 doxygen
      - name: Install Dependencies (Linux)
        run: sudo apt-get install doxygen
        if: matrix.os == 'ubuntu-latest'
      - name: Install Dependencies (macOS)
        run: brew install doxygen automake
        if: matrix.os == 'macos-latest'
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: before install
        run: |
          mkdir gauopen
          mkdir mqc-install
          cd gauopen
          wget http://gaussian.com/g16/gauopen_v2.zip
          unzip gauopen_v2.zip
          cd ..
          pwd
          ls
      - name: install
        run: |
          echo -e "yG$GITHUB_WORKSPACE/mqc-install\n-lblas\n-llapack\n$GITHUB_WORKSPACE/gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile
        




