name: continuous integration
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] 
    steps:
            #      - name: get software
            #        - os: ubuntu-latest 
            #          run: |
            #            sudo apt-get update
            #            sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev libopenblas-base libopenblas-dev doxygen
            #        - os: macos-latest
            #          run: |
            #            brew update
            #            brew install m4 doxygen
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: before install
        run: |
          mkdir gauopen
          mkdir mqc-install
          cd gauopen
          wget http://gaussian.com/g16/gauopen_v2.zip
          unzip gauopen_v2.zip
          cd ..
          pwd
          #      - name: install
          #        run: |
          #          echo -e "yG\./mqc-install\n-lblas\n-llapack\n\./gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile
        




