name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] 
    steps:
      - name: Install dependencies (Linux)
        run: sudo apt-get install doxygen
             sudo apt-get install libopenblas-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install dependencies (macOS)
        run: |
          brew install doxygen automake 
          brew reinstall gcc
        if: matrix.os == 'macos-latest'
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Before install
        run: |
          mkdir gauopen
          mkdir mqc-install
          cd gauopen
          wget http://gaussian.com/g16/gauopen_v2.zip
          unzip gauopen_v2.zip
          cd ..
          pwd
          ls
      - name: Install
        run: |
          echo -e "yG$GITHUB_WORKSPACE/mqc-install\n-lblas\n-llapack\n$GITHUB_WORKSPACE/gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile
        




